=== lecras13/Flowers/src/test/java/com/epam/flowers/datatest/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/flowers"
        xmlns:tns="http://www.example.com/flowers"
        elementFormDefault="qualified">

    <!--Flowers ___________________________________________________________________________________________-->
    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:flower" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="flower" type="tns:Flower" abstract="true"/>
    <element name="wildFlower" type="tns:WildFlower" substitutionGroup="tns:flower"/>
    <element name="homeFlower" type="tns:HomeFlower" substitutionGroup="tns:flower"/>


    <!--Flower ____________________________________________________________________________________________-->
    <complexType name="Flower">
        <sequence>
            <element name="soil" type="tns:Soil"/>
            <element name="color" type="tns:Color"/>
            <element name="growingTips" type="tns:GrowingTips"/>
        </sequence>
        <attribute name="nameFlower" type="tns:NameFlower" use="required"/>
        <attribute name="origin" type="string" use="optional"/>
        <attribute name="reproduction" type="tns:Reproduction" use="optional" default="by_seed"/>
    </complexType>

    <!--WildFlower ________________________________________________________________________________________-->
    <complexType name="WildFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="region" type="tns:Region"/>
                    <element name="thornsPresence" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <!--HomeFlower ________________________________________________________________________________________-->
    <complexType name="HomeFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="optimalHumidity" type="positiveInteger"/>
                    <element name="leafDischarge" type="boolean"/>
                    <element name="fruitPresence" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <!--ENUMS -->
    <!--Color -->
    <simpleType name="Color">
        <restriction base="string">
            <enumeration value="blue"></enumeration>
            <enumeration value="green"></enumeration>
            <enumeration value="lilac"></enumeration>
            <enumeration value="pink"></enumeration>
            <enumeration value="purple"></enumeration>
            <enumeration value="red"></enumeration>
            <enumeration value="white"></enumeration>
            <enumeration value="yellow"></enumeration>
        </restriction>
    </simpleType>
    <!--Region -->
    <simpleType name="Region">
        <restriction base="string">
            <enumeration value="meadow"></enumeration>
            <enumeration value="field"></enumeration>
            <enumeration value="forest"></enumeration>
        </restriction>
    </simpleType>
    <!--Reproduction -->
    <simpleType name="Reproduction">
        <restriction base="string">
            <enumeration value="by_leave"></enumeration>
            <enumeration value="by_stalk"></enumeration>
            <enumeration value="by_seed"></enumeration>
        </restriction>
    </simpleType>
    <!--Soil -->
    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="podzolic"></enumeration>
            <enumeration value="unpaved"></enumeration>
            <enumeration value="sod_podzolic"></enumeration>
        </restriction>
    </simpleType>

    <!--Name -->
    <simpleType name="NameFlower">
        <restriction base="ID">
            <pattern value="([a-zA-Z\-]+){1,20}"/>
        </restriction>
    </simpleType>
    <!--GrowingTips -->
    <complexType name="GrowingTips">
        <sequence>
            <element name="temperature" type="integer"/>
            <element name="lightLoving" type="boolean"/>
            <element name="wateringForWeek" type="positiveInteger"/>
        </sequence>
    </complexType>



</schema>

=== lecras13/Flowers/src/test/java/com/epam/flowers/datatest/flowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/flowers"
         xsi:schemaLocation="http://www.example.com/flowers flowers.xsd">

    <!--WildFlower ________________________________________________________________________________________-->
    <wildFlower nameFlower="Chelidonium" origin="Europe-Japan" reproduction="by_seed">
        <soil>sod_podzolic</soil>
        <color>yellow</color>
        <growingTips>
            <temperature>10</temperature>
            <lightLoving>true</lightLoving>
            <wateringForWeek>1000</wateringForWeek>
        </growingTips>
        <region>meadow</region>
        <thornsPresence>false</thornsPresence>
    </wildFlower>

    <wildFlower nameFlower="Cornflower" origin="Europe-Asia" reproduction="by_seed">
        <soil>podzolic</soil>
        <color>blue</color>
        <growingTips>
            <temperature>20</temperature>
            <lightLoving>true</lightLoving>
            <wateringForWeek>1000</wateringForWeek>
        </growingTips>
        <region>field</region>
        <thornsPresence>false</thornsPresence>
    </wildFlower>

    <!--HomeFlower ________________________________________________________________________________________-->
    <homeFlower nameFlower="Abutilon" origin="Brazilia-South_America" reproduction="by_seed">
        <soil>unpaved</soil>
        <color>red</color>
        <growingTips>
            <temperature>25</temperature>
            <lightLoving>true</lightLoving>
            <wateringForWeek>1500</wateringForWeek>
        </growingTips>
        <optimalHumidity>70</optimalHumidity>
        <leafDischarge>false</leafDischarge>
        <fruitPresence>false</fruitPresence>
    </homeFlower>

    <homeFlower nameFlower="Gasteria" origin="South_America" reproduction="by_stalk">
        <soil>podzolic</soil>
        <color>green</color>
        <growingTips>
            <temperature>24</temperature>
            <lightLoving>true</lightLoving>
            <wateringForWeek>400</wateringForWeek>
        </growingTips>
        <optimalHumidity>40</optimalHumidity>
        <leafDischarge>false</leafDischarge>
        <fruitPresence>false</fruitPresence>
    </homeFlower>
</flowers>
